services:
  
  catalogue:
     build: ./catalogue
     image: ravid145/catalogue:1.0.0
     container_name: catalogue
     depends_on:
     - mongodb
  user:
    build: ./user
    image: user:1.0.0
    container_name: user
    depends_on:
    - redis

  frontend:
    build: ./frontend
    image: frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user


  mongodb: 
    build: ./mongodb # it moves to mongodb directory
    image: ravid145/mongodb:1.0.0 # docker build -t ravid145/mongodb:1.0.0
    container_name: mongodb

  redis:
    image: redis:7.0
    container_name: redis

networks:
  default:
    driver: bridge
    name: roboshop
    external: false # it it true you need to create network manullay
